name: Deploy Chamilo to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Install PHP dependencies
      run: composer install --no-dev --optimize-autoloader --no-scripts

    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: 20

    - name: Install JS dependencies
      run: npm install

    - name: Build frontend
      run: npm run build

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ipfl-training-academy'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: .
